<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);IDE1006;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API_SourceBase.Data\API_SourceBase.Data.csproj" />
    <ProjectReference Include="..\API_SourceBase.Models\API_SourceBase.Models.csproj" />
    <ProjectReference Include="..\API_SourceBase.Utilities\API_SourceBase.Utilities.csproj" />
  </ItemGroup>

</Project>
