<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);IDE1006;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API_SourceBase.Application\API_SourceBase.Application.csproj" />
    <ProjectReference Include="..\API_SourceBase.Data\API_SourceBase.Data.csproj" />
    <ProjectReference Include="..\API_SourceBase.Models\API_SourceBase.Models.csproj" />
    <ProjectReference Include="..\API_SourceBase.Utilities\API_SourceBase.Utilities.csproj" />
  </ItemGroup>

</Project>
